### ISSUE TITLE
แก้ไขในส่วนของเว็บนะคะ 

### ISSUE THREAD

**Issue by kanoknapa** [SEUP/cattleVueMobile#27]
![image](https://user-images.githubusercontent.com/44282476/47601592-4d33e500-d9fd-11e8-88c1-937d4814559b.png)
![image](https://user-images.githubusercontent.com/44282476/47601601-6d63a400-d9fd-11e8-89a5-de99264d08f2.png)

*ตรงที่เราจะส่งออกข้อมูลค่ะ มันผิดพลาดที่เบอร์หู มันไม่ตรงกับข้อมูลเดิม

**Comment by pchaow** [comment]
ok
