### ISSUE TITLE
แก้ไขส่วนของเว็บ *ในส่วนโคแรกเกิด

### ISSUE THREAD

**Issue by kanoknapa** [SEUP/cattleVueMobile#28]
![image](https://user-images.githubusercontent.com/44282476/47601925-545cf200-da01-11e8-9007-56ce28191f66.png)

*ตรงที่โคแรกเกิด 
*วัน/เดือน/ปี ที่เกิดกับข้อมูลหย่านมค่ะมันไม่ตรงกัน  แล้วก็อายุ

**Comment by pchaow** [comment]
แก้ให้วันเดือนปีตรงกัน
อายุแก้ไม่ได้ เป็นข้อผิดพลาดของผู้ใช้
