### ISSUE TITLE
ในส่วนของเว็ป แผนภูมิรายงาน

### ISSUE THREAD

**Issue by Apinyamanotham** [SEUP/cattleVueMobile#29]
แผนภูมิรายงาน เหมือนข้อมูลจะผิดพลาดนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47601825-24611f00-da00-11e8-82e9-fab2987aef84.png)
พื้นที่ถือครองของเกษตรกร ต้องเหมือนกับ พื้นที่ที่ใช้ในการเลี้ยงโคเนื้อ หรือป่าวค่ะ
พื้นที่ถือครองทางการเกษตร ตก กร
![image](https://user-images.githubusercontent.com/44282511/47602093-c33b4a80-da03-11e8-81b6-2649397a89f8.png)
![image](https://user-images.githubusercontent.com/44282511/47602113-0d243080-da04-11e8-8428-c533748d157c.png)
พื้นที่ที่ใช้ในการเลี้ยงโคเนื้อ เลือกดูแต่ละจจังหวัดแล้ว กราฟเหมือนกันทุกจังหวัดเลย 
![image](https://user-images.githubusercontent.com/44282511/47602145-8de32c80-da04-11e8-9ec2-f0cb3c82ed62.png)
รวมขนาดพื้นที่(ไร่) แยก      ***รวมขนาดพื้นที่ (ไร่) แยก ตรงไร่ อย่าลืมเว้นวรรคด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602182-1c57ae00-da05-11e8-92b1-59de88f41183.png)
จำนวนแรงงานภายในครอบครัว จำนวนแรงงานภายนอกครอบครัว ตัวเลขมันยังไงๆ ก็ไม่รู้มันต้อง 1 ถึง 2, 2 ถึง 3 หรือป่าว จำนวนเลขไม่ตรงด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602295-1d89da80-da07-11e8-8123-693e8a3e66ff.png)
อาสาปศุสัตว์(อ.ส.ป) เว้นด้วยนะค่ะ อาสาปศุสัตว์ (อ.ส.ป) 
![image](https://user-images.githubusercontent.com/44282511/47602347-d6501980-da07-11e8-992e-28b4557a194a.png)
วัคซีนป้องกันโรค จำนวนเหมือนกันทุกจังหวัดเลยแก้ไขด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602381-524a6180-da08-11e8-9f20-1975f1e63eba.png)
![image](https://user-images.githubusercontent.com/44282511/47602383-60987d80-da08-11e8-8785-0bfd2d243d3c.png)
การเกิดโรคในฟาร์ม ทำไมมีแต่โรคแท้งติดต่อ
![image](https://user-images.githubusercontent.com/44282511/47602431-1794f900-da09-11e8-82a4-8531aeac7317.png)
![image](https://user-images.githubusercontent.com/44282511/47602436-1e237080-da09-11e8-9435-4b933b0ffc01.png)
การขึ้นทะเบียนฟาร์มกับภาครัฐ จำนวนเหมือนกันทุกจังหวัดเลยแก้ไขด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602453-617ddf00-da09-11e8-8eaa-411751d5575e.png)
ใต่ตารางเว้นด้วยนะค่ะ 
![image](https://user-images.githubusercontent.com/44282511/47602486-e1a44480-da09-11e8-85a5-357ed33a0f86.png)
อัตราส่วนพ่อพันธุ์คุมฝูง ใต้ตารางตัวเลขผิดหรือป่าวค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602540-afdfad80-da0a-11e8-9bae-8a0583253014.png)
การถ่ายพยาธิ ข้างในเป็นเงินทุนที่ท่านใช้เลี้ยงโคเนื้อ
![image](https://user-images.githubusercontent.com/44282511/47602567-ee756800-da0a-11e8-8e22-5cc6d4d0217b.png)
การจัดการมูลโคในฟาร์ม ใต้ตารางเว้นวรรคด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602587-3e542f00-da0b-11e8-8bb2-a541ea843f20.png)
ราคาของโคเนื้อที่ขาย และระยะเวลาในการเลี้ยง ***การจำหน่าย
![image](https://user-images.githubusercontent.com/44282511/47602635-e23dda80-da0b-11e8-8f0f-e9dfb341771c.png)
ระดับความพอใจต่อราคาที่ขาย ***การจำหน่าย
![image](https://user-images.githubusercontent.com/44282511/47602660-25984900-da0c-11e8-91c1-deaa5cbe0508.png)
หน่วยงานที่ให้บริการส่งเสริมการเลี้ยงโคเนื้อ ใต้ตารางเว้นวรรคด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602673-48c2f880-da0c-11e8-9722-410f66829f2f.png)
อาชีพการเลี้ยงโคเนื้อ (อาชีพหลัก-เสริม) เว้นวรรคด้วยนะค่ะ
![image](https://user-images.githubusercontent.com/44282511/47602705-c424aa00-da0c-11e8-9bff-a9bb8807c19e.png)
ค่าใช้จ่ายในการเลี้ยงโคเนื้อ (บาท ต่อ เดือน) ตัวเลขใต้ตราง ยังไงอยู่นะคะ่
![image](https://user-images.githubusercontent.com/44282511/47602725-02ba6480-da0d-11e8-8e19-b7597162af59.png)
ฝากการเว้นวรรคใน ***บันทึกข้อมูลเกษตรกรใหม่ ด้วยนะค่ะ

**Comment by pchaow** [comment]
แก้เรียบร้อยละครับ ถ้าเจออีกก็ขึ้นโพสใหม่นะครับ
ส่วนใหญ่ที่เว้นวรรค จะเกิดจากข้อมูลครับ แก้ที่เดียวมันจะกระทบไปกันหมด
